---

- name: Create the network configuration file for bridge devices
  template:
    src: bridge.j2
    dest: "{{ net_path }}/ifcfg-{{ item.device }}"
  with_items: network_bridge_interfaces
  when: network_bridge_interfaces is defined
  register: bridge_result

- name: Write configuration files for rhel route configuration
  template:
    src: route.j2
    dest: "{{ net_path }}/route-{{ item.device }}"
  with_items: network_bridge_interfaces
  when: network_bridge_interfaces is defined and item.route is defined and ansible_os_family == 'RedHat'

- name: Bringing up interfaces
  shell: ifdown {{ item.item.device }}; ifup {{ item.item.device }}
  with_items: bridge_result.results
  when: bridge_result is defined and item.changed

- name: Create the network configuration file for port on the bridge devices
  template:
    src: bridge_port.j2
    dest: "{{ net_path }}/ifcfg-{{ item.1 }}"
  with_subelements:
   - network_bridge_interfaces
   - ports
  when: network_bridge_interfaces is defined
  register: bridge_port_result

- name: Bringing up interfaces
  shell: ifdown {{ item.item.1 }}; ifup {{ item.item.1 }}
  with_items: bridge_port_result.results
  when: bridge_port_result is defined and item.changed
